const STATUSES = {
  CREATED: "CREATED",
  ANALYZED: "ANALYZED",
  OPEN_FOR_DRIVERS: "OPEN_FOR_DRIVERS",
  DRIVER_ACCEPTED: "DRIVER_ACCEPTED",
  ROUTE_OPTIMIZED: "ROUTE_OPTIMIZED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  ISSUE_REPORTED: "ISSUE_REPORTED",
};

const TRANSITIONS = {
  CREATED: ["ANALYZED", "ISSUE_REPORTED"],
  ANALYZED: ["OPEN_FOR_DRIVERS", "ISSUE_REPORTED"],
  OPEN_FOR_DRIVERS: ["DRIVER_ACCEPTED", "ISSUE_REPORTED"],
  DRIVER_ACCEPTED: ["ROUTE_OPTIMIZED", "PICKED_UP", "ISSUE_REPORTED"],
  ROUTE_OPTIMIZED: ["PICKED_UP", "ISSUE_REPORTED"],
  PICKED_UP: ["IN_TRANSIT", "ISSUE_REPORTED"],
  IN_TRANSIT: ["DELIVERED", "ISSUE_REPORTED"],
  DELIVERED: ["CONFIRMED", "ISSUE_REPORTED"],
  CONFIRMED: ["COMPLETED", "ISSUE_REPORTED"],
  COMPLETED: [],
  ISSUE_REPORTED: [],
};

function canTransition(from, to) {
  if (!STATUSES[to]) return false;
  return (TRANSITIONS[from] || []).includes(to);
}

module.exports = { STATUSES, TRANSITIONS, canTransition };
